"""Added run_id to document and version

Revision ID: 2cd3b65dfa37
Revises: 2c1bc23fef4a
Create Date: 2025-10-18 14:28:41.006359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2cd3b65dfa37'
down_revision: Union[str, Sequence[str], None] = '2c1bc23fef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_versions_run_id'), 'document_versions', ['run_id'], unique=False)
    op.create_foreign_key(None, 'document_versions', 'runs', ['run_id'], ['id'])
    op.add_column('documents', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_run_id'), 'documents', ['run_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_run_id'), table_name='documents')
    op.drop_column('documents', 'run_id')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_index(op.f('ix_document_versions_run_id'), table_name='document_versions')
    op.drop_column('document_versions', 'run_id')
    # ### end Alembic commands ###
